<?php

declare(strict_types=1);
/*
 * Copyright (c) Ratepay GmbH
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ratepay\RpayPayments\Components\DeviceFingerprint;

use Shopware\Core\Checkout\Order\OrderEntity;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Symfony\Component\HttpFoundation\Request;

interface DfpServiceInterface
{
    /**
     * @param OrderEntity|SalesChannelContext $baseData
     */
    public function generatedDfpId(Request $request, $baseData): ?string;

    /**
     * @param OrderEntity|SalesChannelContext $baseData
     */
    public function getDfpSnippet(Request $request, $baseData): ?string;

    /**
     * validates the dfp-id if the id has been generated by the plugin, or if it has been modified
     * @param OrderEntity|SalesChannelContext $baseData
     */
    public function isDfpIdValid($baseData, string $dfpId = null): bool;

    /**
     * @param OrderEntity|SalesChannelContext $object
     */
    public function isDfpRequired($object): bool;
}
